name: Deploy Lambda

on:
  push:
    paths:
      - 'lambda_code/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check environment variables
      run: |
        echo "Region: $AWS_REGION"
        if [ -z "$AWS_REGION" ]; then
          echo "❌ AWS_REGION is not set"
          exit 1
        fi

    - name: Zip Lambda function
      run: |
        cd lambda
        zip -r ../lambda_payload.zip evaluate_stock_strategy.py

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name GetStockPrice \
          --zip-file fileb://lambda_payload.zip \
          --region $AWS_REGION
