name: Deploy Lambda

on:
  push:
    paths:
      - 'lambda/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Zip Lambda function
      run: |
        cd lambda
        zip -r ../lambda_payload.zip get_stock_price.py

    - name: Deploy to AWS Lambda
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws lambda update-function-code \
          --function-name GetStockPrice \
          --zip-file fileb://lambda_payload.zip \
          --region $AWS_REGION
