name: Deploy Lambda

on:
  push:
    paths:
      - 'lambda_code/**'
      - 'tests/**'
      - 'requirements-dev.txt'
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ALPHA_VANTAGE_KEY: ${{ secrets.ALPHA_VANTAGE_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install test dependencies
      run: python3 -m pip install -r requirements-dev.txt

    - name: Run unit tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/lambda_code
        python3 -m pytest lambda_code/tests

    - name: Check environment variables
      run: |
        echo "Region: $AWS_REGION"
        if [ -z "$AWS_REGION" ]; then
          echo "❌ AWS_REGION is not set"
          exit 1
        fi

    - name: Zip Lambda function
      run: |
        cd lambda_code
        zip -r ../lambda_payload.zip evaluate_stock_strategy.py

    - name: Upload Lambda ZIP artifact
      uses: actions/upload-artifact@v3
      with:
        name: lambda_payload
        path: lambda_payload.zip

    - name: Deploy via custom script
      run: ./scripts/deploy_lambda.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ env.AWS_REGION }}

